use clap::ValueEnum;
use std::io::{self, IsTerminal, Write};

#[derive(Clone, Copy, Debug, Default, ValueEnum)]
pub enum ColorMode {
    #[default]
    Auto,
    Always,
    Never,
}

pub fn use_color(mode: ColorMode, stdout: &io::Stdout) -> bool {
    match mode {
        ColorMode::Always => true,
        ColorMode::Never => false,
        ColorMode::Auto => {
            stdout.is_terminal()
                && std::env::var_os("NO_COLOR").is_none()
                && std::env::var("TERM").as_deref() != Ok("dumb")
        }
    }
}

struct FileExample {
    name: &'static str,
    content: &'static str,
}

struct Example {
    title: &'static str,
    description: &'static str,
    shell: &'static str,
    files: &'static [FileExample],
}

const fn example(title: &'static str, description: &'static str, shell: &'static str) -> Example {
    Example {
        title,
        description,
        shell,
        files: &[],
    }
}

struct Section {
    title: &'static str,
    description: &'static str,
    examples: &'static [Example],
}

const SECTIONS: &[Section] = &[
    Section {
        title: "Start here: local encryption",
        description: "Create a recipient, store values and read them back without a server.",
        examples: &[
            example(
                "Create a v3 key and secured template",
                "Run in a new directory. init defaults to API 3.0 and creates a local hybrid key bundle. --create-file creates env.secured.json and refuses to overwrite it. Use the same ENCJSON_KEYDIR for later commands.",
                r#"export ENCJSON_KEYDIR="$PWD/keys"
encjson init --api 3.0 --create-file
encjson set -f env.secured.json APP_NAME demo -w
encjson set -f env.secured.json DB_PASSWORD demo-password -w
encjson decrypt -f env.secured.json"#,
            ),
            example(
                "Inspect local keys and file metadata",
                "list (alias ls) lists local public key references; info shows the file's recipient and key resolution. Neither command edits the input file.",
                "encjson list\nencjson info -f env.secured.json",
            ),
            example(
                "Encrypt or decrypt an existing file",
                "The JSON must already contain recipient metadata; retain the _recipient_key generated by init (or legacy _public_key). Without -w, input is unchanged and transformed JSON goes to stdout. These are alternative commands, not one sequence.",
                "encjson encrypt -f env.secured.json\nencjson encrypt -f env.secured.json -w\nencjson decrypt env.secured.json\nencjson decrypt -f env.secured.json -w",
            ),
        ],
    },
    Section {
        title: "Unsecured JSON and output formats",
        description: "Read plain JSON too; environment exports use the environment object (or env alias).",
        examples: &[
            Example {
                files: &[FileExample {
                    name: "env.unsecured.json",
                    content: r#"{
  "environment": {
    "APP_NAME": "demo",
    "HOST": "localhost",
    "API_URL": "https://{env:HOST}/api",
    "REPLICAS": 2,
    "FEATURE_ENABLED": true
  }
}"#,
                }],
                ..example(
                    "Export JSON as shell or dot-env",
                    "JSON output preserves JSON types. Shell/dot-env output exports environment values and resolves {env:NAME} references from the document, then process environment. Output redirection belongs to the shell; -o selects the format, not a destination filename.",
                    "encjson decrypt -f env.unsecured.json -o json\nencjson decrypt -f env.unsecured.json -o shell\nencjson decrypt -f env.unsecured.json -o dot-env > environment.env",
                )
            },
            example(
                "Load decrypted exports into the current shell",
                "Use decrypt -o shell for new scripts; the env subcommand is its deprecated shortcut. -w is valid only with JSON output and a file input.",
                r#"eval "$(encjson decrypt -f env.secured.json -o shell)""#,
            ),
            example(
                "Read exactly one value",
                "--env-name prints the selected value without export syntax. It names a JSON environment key; --env elsewhere names a policy scope.",
                "encjson decrypt -f env.secured.json --env-name DB_PASSWORD",
            ),
            example(
                "Read JSON from stdin",
                "A positional - or -f - selects stdin; omitting a file also reads stdin. In-place writes need a real file.",
                "cat env.secured.json | encjson decrypt -o dot-env -\ncat env.secured.json | encjson decrypt -f - -o json\ncat env.secured.json | encjson encrypt -",
            ),
        ],
    },
    Section {
        title: "Edit values and automate updates",
        description: "set and unset operate on environment/env; secured files are decrypted and re-encrypted internally.",
        examples: &[
            example(
                "Preview and save a string change",
                "Without -w, set prints updated JSON; with -w it overwrites the input. Strings in a secured environment remain encrypted in the saved file.",
                "encjson set -f env.secured.json API_URL https://api.example.com\nencjson set -f env.secured.json API_URL https://api.example.com -w",
            ),
            example(
                "Store a JSON number, boolean or object",
                "--json-value parses VALUE as JSON. Only string values are encrypted; numbers and booleans remain visible. Use strings for values that must be encrypted.",
                r#"encjson set -f env.unsecured.json REPLICAS 3 --json-value -w
encjson set -f env.unsecured.json FEATURE_ENABLED true --json-value -w
encjson set -f env.unsecured.json SETTINGS '{"timeout":30,"enabled":true}' --json-value -w"#,
            ),
            example(
                "Remove a value",
                "Omit -w to inspect the resulting JSON first.",
                "encjson unset -f env.secured.json OLD_PASSWORD\nencjson unset -f env.secured.json OLD_PASSWORD -w",
            ),
            example(
                "Use the terminal editor",
                "Opens an interactive editor for environment/env values. --ui is optional; --web is reserved and currently unsupported.",
                "encjson edit -f env.secured.json --ui",
            ),
        ],
    },
    Section {
        title: "Key rotation and format migration",
        description: "rotate-key changes the recipient; migrate-format changes a legacy document to API 3.0.",
        examples: &[
            example(
                "Rotate and save a secured file",
                "Requires the old private material. Generates and stores new local key material, then saves re-encrypted JSON. Without -w it still creates a key and prints both JSON and status messages; it is not a dry-run or a clean JSON export. Aliases: rekey, migrate-key.",
                "encjson rotate-key -f env.secured.json -w",
            ),
            example(
                "Rotate to an existing v3 recipient",
                "Set RECIPIENT_ID to a key_id reported by init/list. The target bundle must be in the local key directory; --recipient is supported only for v3 rotation.",
                r#"export RECIPIENT_ID='replace-with-existing-v3-key-id'
encjson rotate-key -f env.secured.json --recipient "$RECIPIENT_ID" -w"#,
            ),
            example(
                "Migrate a legacy file to API 3.0",
                "Requires its old private key. Supports legacy API 1.0/2.0 input with _public_key; currently only --to 3.0 is implemented. A new local v3 bundle is generated unless --recipient selects an existing one.",
                "encjson migrate-format -f legacy.secured.json --to 3.0 -w",
            ),
            example(
                "Generate a legacy pair when interoperability requires it",
                "API 2.0 is explicit, not the default. init prints the legacy private key; run it outside recorded CI logs.",
                "encjson init --api 2.0 -k ./legacy-keys",
            ),
        ],
    },
    Section {
        title: "Virtual filesystem assets",
        description: "Bundle ordinary files as base64 contents in JSON; list, extract or export them later.",
        examples: &[
            Example {
                files: &[FileExample {
                    name: "assets.unsecured.json",
                    content: r#"{
  "assets": {
    "config/app.txt": {
      "content": "SGVsbG8K",
      "kind": "text"
    }
  }
}"#,
                }],
                ..example(
                    "Read an asset bundle",
                    "get decodes the stored base64 into original bytes; --base64 returns the stored base64 instead. -o writes an output file. export refuses existing files unless --overwrite is supplied.",
                    "encjson assets list -f assets.unsecured.json\nencjson assets get -f assets.unsecured.json --path config/app.txt\nencjson assets get -f assets.unsecured.json --path config/app.txt --base64\nencjson assets export -f assets.unsecured.json --out-dir ./extracted",
                )
            },
            example(
                "Import a directory",
                "Create ./assets first and populate it with files. import writes the output JSON directly. Mode can also be inferred from .unsecured.json/.secured.json suffixes; explicit flags make the intent clear.",
                "encjson assets import --from-dir ./assets -o assets.unsecured.json --unsecured",
            ),
            example(
                "Create a legacy secured asset bundle",
                "New secured imports use a legacy public key plus its resolvable private key; this import path does not create a v3 recipient bundle. Existing secured imports reuse _public_key. Set PUBLIC_KEY to the 64-hex public key from a legacy init.",
                r#"export PUBLIC_KEY='replace-with-64-hex-public-key'
encjson assets import --from-dir ./assets -o assets.secured.json \
    --secured --public-key "$PUBLIC_KEY" -k ./legacy-keys
encjson assets get -f assets.secured.json --path config/app.txt -o app.txt -k ./legacy-keys"#,
            ),
        ],
    },
    Section {
        title: "Sidecar transforms and Kubernetes Secrets",
        description: "Render YAML locally; these commands do not apply anything to a Kubernetes cluster.",
        examples: &[
            Example {
                files: &[FileExample {
                    name: "mtls.secured.schema.json",
                    content: r#"{
  "MTLS_*": {"encoding": "base64", "normalize_line_endings": true},
  "*": {"encoding": "plain", "normalize_line_endings": false}
}"#,
                }],
                ..example(
                    "Decode base64 values after decryption",
                    "The sidecar is discovered next to mtls.secured.json. Exact keys win over longest-prefix patterns, then *. Sidecars apply to decrypt and value Secret rendering, not arbitrary stdin without a file path.",
                    "encjson decrypt -f mtls.secured.json",
                )
            },
            example(
                "Render one Opaque Secret from environment values",
                "Maps a decrypted environment value to a Secret data key. -o here selects the output file, unlike decrypt -o which selects a format. Values in the manifest are base64, not EncJson ciphertext.",
                "encjson render-k8s-secret -f env.secured.json \\\n    --name demo-config --namespace demo-dev --secret-type Opaque \\\n    --from-env DB_PASSWORD=password -o demo-config-secret.yml",
            ),
            example(
                "Render a TLS Secret",
                "Create mtls.secured.json containing MTLS_TLS_CRT, MTLS_TLS_KEY and MTLS_CA_CRT. The default TLS type requires tls.crt, tls.key and ca.crt in this tool.",
                "encjson render-k8s-secret -f mtls.secured.json \\\n    --name demo-mtls --namespace demo-dev \\\n    --from-env MTLS_TLS_CRT=tls.crt \\\n    --from-env MTLS_TLS_KEY=tls.key \\\n    --from-env MTLS_CA_CRT=ca.crt",
            ),
            example(
                "Render multiple Secrets in one YAML stream",
                "--from-env-secret maps ENV_KEY=secretName/secretKey; --name is unnecessary in this mode.",
                "encjson render-k8s-secret -f env.secured.json \\\n    --namespace demo-dev --secret-type Opaque \\\n    --from-env-secret DB_PASSWORD=demo-db/password \\\n    --from-env-secret API_URL=demo-api/url",
            ),
            example(
                "Render runtime decryption key material",
                "API 3.0 produces expanded ENCJSON_* key fields; API 2.0 produces public-key/private-key fields. This manifest contains private key material, not just encrypted application values.",
                "encjson render-k8s-pair-secret -f env.secured.json \\\n    --name demo-encjson-keys --namespace demo-dev -o demo-key-secret.yml",
            ),
        ],
    },
    Section {
        title: "Key resolution and provider inputs",
        description: "Pass these options to commands that resolve keys (e.g. decrypt/info/set). They are not universal top-level flags.",
        examples: &[
            example(
                "Choose the local key directory",
                "-k/--keydir overrides ENCJSON_KEYDIR; otherwise encjson uses the OS-specific default directory. API 3.0 recipient bundles are resolved from the local key store.",
                "encjson decrypt -f env.secured.json -k /etc/encjson",
            ),
            example(
                "Use legacy key material from process environment",
                "Replace both values with real 64-hex keys matching the document's _public_key. Provider-based resolution applies to legacy public/private pairs; it does not fetch v3 bundles. A direct ENCJSON_PRIVATE_KEY override is also supported for legacy resolution.",
                r#"export ENCJSON_PUBLIC_KEY='replace-with-64-hex-public-key'
export ENCJSON_PRIVATE_KEY='replace-with-64-hex-private-key'
encjson decrypt -f legacy.secured.json --key-source env"#,
            ),
            example(
                "Resolve a legacy pair through remote mTLS",
                "Provide the remote key provider URL, client certificate/key and CA bundle. --env is a policy environment; --env-name selects a document value. Scope-required validates tenant/environment inputs.",
                "encjson decrypt -f legacy.secured.json \\\n    --key-source remote-mtls \\\n    --remote-keys-url https://keys.example.com \\\n    --remote-tls-cert-file client.crt \\\n    --remote-tls-key-file client.key \\\n    --remote-tls-ca-file ca.crt \\\n    --tenant demo --env dev --scope-required",
            ),
            example(
                "Resolve a legacy pair through Vault",
                "Set ENCJSON_VAULT_TOKEN through your session or CI secret variables. CLI options override matching ENCJSON_* environment variables.",
                "encjson decrypt -f legacy.secured.json \\\n    --key-source vault \\\n    --vault-addr https://vault.example.com \\\n    --vault-path secret/data/demo/encjson \\\n    --vault-public-field public-key \\\n    --vault-private-field private-key",
            ),
            example(
                "Resolve a legacy pair through Conjur",
                "Set ENCJSON_CONJUR_AUTHN_API_KEY through your session or CI secret variables; public/private variable IDs identify key material in Conjur.",
                "encjson decrypt -f legacy.secured.json \\\n    --key-source conjur \\\n    --conjur-appliance-url https://conjur.example.com \\\n    --conjur-account demo \\\n    --conjur-authn-login host/demo-app \\\n    --conjur-public-variable-id demo/public-key \\\n    --conjur-private-variable-id demo/private-key \\\n    --conjur-ca-cert-file ca.crt",
            ),
        ],
    },
    Section {
        title: "Login, registration and synchronization",
        description: "These examples contact a keys service; replace URLs, scopes, key references and credentials with your own.",
        examples: &[
            example(
                "Log in and manage saved sessions",
                "login performs browser-based OIDC with a local callback (default port 8181). Session name and OIDC client are independent of the keys API URL. status reports the active session; sessions use changes it.",
                "encjson login --url https://login.example.com --client cli-tools --server demo --port 8181\nencjson status\nencjson sessions list\nencjson sessions use demo\nencjson logout --server demo",
            ),
            example(
                "Submit one local key for approval",
                "Set KEY_REF to a local v3 key_id or legacy public key from init/list. --tenant and --note are required for explicit registration. Uses ENCJSON_ACCESS_TOKEN or the active login session. Registration submits a pending request; it does not approve it.",
                r#"export ENCJSON_KEYS_URL='https://keys.example.com'
export KEY_REF='replace-with-local-key-reference'
encjson register "$KEY_REF" --tenant demo --note 'Development environment' --tag dev"#,
            ),
            example(
                "Download approved key material",
                "Uses the same keys URL and access-token/session inputs. Choose a document, one key or all visible keys; existing local key files are skipped. The local directory is ENCJSON_KEYDIR or -k.",
                r#"export ENCJSON_KEYS_URL='https://keys.example.com'
export KEY_REF='replace-with-approved-key-reference'
encjson sync -f env.secured.json
encjson sync --key "$KEY_REF"
encjson sync"#,
            ),
            example(
                "Preview local directory synchronization",
                "sync-dir is filesystem-only. It copies missing key filenames and skips existing ones; --dry-run writes nothing.",
                "encjson sync-dir --src-dir ./keys --dst-dir ./keys-copy --dry-run\nencjson sync-dir --src-dir ./keys --dst-dir ./keys-copy",
            ),
        ],
    },
    Section {
        title: "Completion, diagnostics and this guide",
        description: "Use command-specific --help for the full argument list.",
        examples: &[
            example(
                "Generate completion for your shell",
                "Supported shells include bash, zsh, fish, powershell and elvish. Source or install the generated script as required by your shell.",
                "encjson completion zsh > encjson.zsh",
            ),
            example(
                "Version and tracing",
                "-v/--version prints the binary version. --debug enables stderr tracing; --quiet (or ENCJSON_QUIET=true) suppresses encjson warnings.",
                "encjson --version\nencjson decrypt -f env.secured.json --debug\nencjson decrypt -f env.secured.json --quiet",
            ),
            example(
                "Read or save these examples",
                "examples (alias example) reads no input/key files and contacts no service. Automatic color respects NO_COLOR and TERM=dumb; redirected output is plain text.",
                "encjson examples\nencjson examples --color never > encjson-examples.txt\nencjson decrypt --help",
            ),
        ],
    },
];

fn paint(value: &str, style: &str, color: bool) -> String {
    if color {
        format!("\x1b[{style}m{value}\x1b[0m")
    } else {
        value.to_owned()
    }
}

pub fn write_examples(writer: &mut impl Write, color: bool) -> io::Result<()> {
    writeln!(writer, "{}", paint("ENCJSON EXAMPLES", "1;36", color))?;
    writeln!(
        writer,
        "FILE blocks are inputs to create; SHELL blocks are commands to run."
    )?;
    writeln!(
        writer,
        "Sections are alternative workflows, not one script. Replace example paths and credentials."
    )?;
    writeln!(
        writer,
        "Commands normally print JSON to stdout; -w overwrites a file. Strings are encrypted; JSON numbers/booleans are not."
    )?;
    for section in SECTIONS {
        writeln!(
            writer,
            "\n{}\n  {}",
            paint(
                &format!("## {}", section.title.to_uppercase()),
                "1;36",
                color
            ),
            section.description
        )?;
        for example in section.examples {
            writeln!(
                writer,
                "\n  {}\n    {}",
                paint(&format!("> {}", example.title), "1;33", color),
                example.description
            )?;
            for file in example.files {
                writeln!(
                    writer,
                    "\n    {}",
                    paint(&format!("FILE {} (JSON)", file.name), "1;34", color)
                )?;
                for line in file.content.lines() {
                    writeln!(writer, "      {}", paint(line, "34", color))?;
                }
            }
            writeln!(writer, "\n    {}", paint("SHELL", "1;32", color))?;
            for line in example.shell.lines() {
                writeln!(writer, "      {}", paint(line, "32", color))?;
            }
        }
    }
    writeln!(
        writer,
        "\nRun 'encjson <command> --help' for all flags. Full reference: README.md"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Cli, Commands};
    use clap::{CommandFactory, Parser};

    #[test]
    fn examples_and_alias_parse_without_key_resolution() {
        for name in ["examples", "example"] {
            let cli = Cli::try_parse_from(["encjson", name, "--color", "never"]).unwrap();
            assert!(matches!(
                cli.command,
                Some(Commands::Examples {
                    color: ColorMode::Never
                })
            ));
        }
        assert!(Cli::try_parse_from(["encjson", "examples", "--color", "invalid"]).is_err());
        assert!(Cli::try_parse_from(["encjson", "examples", "unexpected-file.json"]).is_err());
    }

    #[test]
    fn plain_guide_covers_commands_and_valid_json_files() {
        let mut output = Vec::new();
        write_examples(&mut output, false).unwrap();
        let output = String::from_utf8(output).unwrap();
        assert!(!output.contains('\x1b'));
        assert!(output.contains("FILE env.unsecured.json (JSON)"));
        assert!(output.contains("SHELL"));
        for command in Cli::command().get_subcommands() {
            // env is deprecated; prefer decrypt -o shell. help is generated by clap.
            if !matches!(command.get_name(), "env" | "help") {
                assert!(
                    output.contains(&format!("encjson {}", command.get_name())),
                    "missing {}",
                    command.get_name()
                );
            }
        }
        for section in SECTIONS {
            for example in section.examples {
                for file in example.files {
                    serde_json::from_str::<serde_json::Value>(file.content).unwrap();
                }
            }
        }
    }

    #[test]
    fn color_does_not_change_guide_content() {
        let mut plain = Vec::new();
        let mut colored = Vec::new();
        write_examples(&mut plain, false).unwrap();
        write_examples(&mut colored, true).unwrap();
        let colored = String::from_utf8(colored).unwrap();
        assert!(colored.contains("\x1b[1;36m"));
        let mut stripped = String::new();
        let mut chars = colored.chars();
        while let Some(ch) = chars.next() {
            if ch == '\x1b' {
                for escaped in chars.by_ref() {
                    if escaped == 'm' {
                        break;
                    }
                }
            } else {
                stripped.push(ch);
            }
        }
        assert_eq!(stripped.as_bytes(), plain);
    }

    #[test]
    fn output_errors_are_propagated() {
        struct BrokenWriter;
        impl Write for BrokenWriter {
            fn write(&mut self, _: &[u8]) -> io::Result<usize> {
                Err(io::Error::new(io::ErrorKind::BrokenPipe, "closed output"))
            }
            fn flush(&mut self) -> io::Result<()> {
                Ok(())
            }
        }
        assert_eq!(
            write_examples(&mut BrokenWriter, false).unwrap_err().kind(),
            io::ErrorKind::BrokenPipe
        );
    }
}
