[package]
name = "encjson-keys-ctl"
version = "0.6.6"
edition = "2024"

[[bin]]
name = "encjson-keys-ctl"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
encjson-core = { workspace = true }
tokio = { workspace = true }
